### ISSUE TITLE
Run asynchronously 

### ISSUE THREAD

**Issue by mauriciogior** [vdemedes/mongorito#12]
Hello,

if I want to run the following code:

```javascript
var post = yield Posts.where("_id", "someid").find();

post.title = "New title";

post.save(); // without yield

var otherPost = yield Posts.where("_id", "someotherid").find();
```

will it work? Since I don't need to wait for the result of `post.save()`, may I run it asynchronously?

**Comment by mauriciogior** [comment]
Also, how do I handle errors?

**Comment by vdemedes** [comment]
Hello, I recommend reading more about ES6 generators and also, read carefully [co's](https://github.com/tj/co) readme, because from these examples I see that you don't fully understand how generators are used with **co**. This is the whole point, your code executes asynchronously (does not block event loop), but you write it in synchronous manner.
