### ISSUE TITLE
Please understand，My English is very poor

### ISSUE THREAD

**Issue by 888dazhuang** [vdemedes/mongorito#34]
//
Post.find({},{name:1,_id:0})
//results  
{ "_id" : ObjectId("551bbfe1ebe85a041dd81c0b"), "name" : "A3" }
{ "_id" : ObjectId("551bc005ebe85a041dd81c0c"), "name" : "A4" }
{ "_id" : ObjectId("551bc01eebe85a041dd81c0d"), "name" : "A4L" }
{ "_id" : ObjectId("551bc025ebe85a041dd81c0e"), "name" : "A6" }
{ "_id" : ObjectId("551bc02cebe85a041dd81c0f"), "name" : "A6L" }
{ "_id" : ObjectId("551bc035ebe85a041dd81c10"), "name" : "Q3" }
.....
// the results Should not include "_id" ,
//I want to get
{ "name" : "A3" }
{ "name" : "A4" }
{ "name" : "A4L" }
{ "name" : "A6" }
{ "name" : "A6L" }
{ "name" : "Q3" }
...

**Comment by maxfrigge** [comment]
You could add a toJSON method to your models, wich filters the object before serialisation.

    class Post extends Model {
        toJSON () {
            var result = super.toJSON();

            delete result._id;

            return result;
        }
    }

**Comment by vdemedes** [comment]
@maxfrigge I would not recommend doing that.
@888dazhuang to achieve this, simply iterate over your documents and `delete post.attributes._id`.

**Comment by maxfrigge** [comment]
@vdemedes Would you mind elaborating why you would rather modify the models directly? Wouldn't that make the models useless (if they loos there id)?

**Comment by vdemedes** [comment]
@maxfrigge by the way, in the code example you provided, you need to execute `toJSON` to run serialization (Mongorito does not execute this method when fetches documents). And also, regarding flexibility, I would not force project-wide serialization of models. Because if I needed `_id` somewhere, I  wouldn't be able to retrieve it.

And as for my `delete` recommendation, I agree, I answered too quickly. It is better to iterate over documents using `.map()` and select only properties, that are required, instead of deleting them.

**Comment by 888dazhuang** [comment]
It seems I can only ‘delete’ the temporary use
