### ISSUE TITLE
Convert to promises

### ISSUE THREAD

**Issue by vdemedes** [vdemedes/mongorito#81]
I think it's time.

**Comment by mgcrea** [comment]
:+1: Would be very interested by a switch to promises.

I'm desperately looking for an ODM designed with ES6 in mind, that supports cross-modules schema definitions. Tried both Mongoose and Camo so far and they both failed the test (tied to their global instances).

Back to the topic, I would highly recommend [bluebird](https://github.com/petkaantonov/bluebird/) for a very performant Promise implementation with a very nice (lodash-like) API. Otherwise defaulting to the native `Promise` constructor with an option to replace it with your own (like [what mongoose is doing](http://mongoosejs.com/docs/promises.html)) is neat.

Moreover, both potential additions to the project missing imo:
- Use `eslint` to enforce a coding standard, I've been using [airbnb's config](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) with a few minor adjustment and it's really nice to have static analysis.
- Use babel as a transpiler (write in ES2015+), gives ES6 imports, class properties, neat defaults... And a wider support (at no extra cost, sourcemaps do work very well today). 

Finally, if you'd like some help I could submit a few PR's.

**Comment by vdemedes** [comment]
Mongorito in master branch is based on Promises now. I'm working on the documentation at the moment, and after that I'll make a major (`2.0.0`) release.

@mgcrea Would love your help on testing the master branch and discovering regressions/bugs before the release, thank you!

**Comment by Clamwinds** [comment]
So do we use the promises native to node right now? Or do we use bluebird?

**Comment by vdemedes** [comment]
Mongorito uses Bluebird, as it's more performant than native promises and provides much more functionality (map, each, etc).

**Comment by vdemedes** [comment]
I've been struggling with time lately, plus all the holidays and stuff, so the release is delayed a bit. Hopefully I'll get to it very soon.

**Comment by ranisalt** [comment]
I'm looking after this move too after switching to Koa 2. You could release a future version prior to updating documentation under `next` tag just like Koa and Koa-related stuff are doing so people can taste awesomeness sooner :smile:

**Comment by vdemedes** [comment]
Sure, good idea! Will do on Thursday.
